const actionTypes = {
  GENERATE_CANDIDATE_MOVES: 'GENERATE_CANDIDATE_MOVES',
  MOVE_PIECE: 'MOVE_PIECE',
  SELECT_PIECE: 'SELECT_PIECE',
  CLEAR_CANDIDATES: 'CLEAR_CANDIDATES',
  TOGGLE_TURN: 'TOGGLE_TURN',
};

export default actionTypes;
